config/routes.rb
Rails.application.routes.draw do

  get 'car/index'
  resources :my_shopping_carts, only: [:create,:destroy]
  get '/add/:product_id', as: :add_to_cart, to: 'my_shopping_carts#create'
  post '/pay', to: 'payments#create'
  get '/checkout', to: 'payments#checkout'
  resources :departaments
  resources :products
  resources :suppliers
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_buttons.html.haml
%button{:id => "product_car_#{product.id}", product:"#{product.id}", class:"btn btn-info mx-2", :onclick => "actions.addCart(this)"}Add Car

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
  %a.navbar-brand{:href => "#"} Sistema de Ventas
  %button.navbar-toggler{ :type => "button", "data-toggle" => "collapse", "data-target" => "#navbarColor01", "aria-controls" => "navbarColor01", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}   
    %span.navbar-toggler-icon
  %navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
    %li.nav-item
    =link_to "Inicio", root_path,class:"btn btn-dark text-white"
    %li.nav-item
    =link_to "Proveedores", suppliers_path,class:"btn btn-dark text-white"
    %li.nav-item
    =link_to "Nuevo Departamento", new_departament_path,class:"btn btn-dark text-white"
    %li.nav-item
    %p.text-white Carrito
    =link_to car_index_path,class:" btn btn-dark" do  
      %i.fa.fa-fw.fa-shopping-cart.fa-lg#mycart.text-white
        = @shopping_cart.products.count
          
          
        
         
     
    