config/routes.rb
Rails.application.routes.draw do

  get 'car/index'
  resources :my_shopping_carts, only: [:create,:destroy]
  get '/add/:product_id', as: :add_to_cart, to: 'my_shopping_carts#create'
  post '/pay', to: 'payments#create'
  get '/checkout', to: 'payments#checkout'
  resources :departaments
  resources :products
  resources :suppliers
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/departament.rb
class Departament < ApplicationRecord
    has_many :product
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :set_departament, only: %i[ show edit update destroy ]


  def show
  end

  def new
    @departament = Departament.new
  end


  def create
    @departament = Departament.new(departament_params)

    respond_to do |format|
      if @departament.save
        format.html { redirect_to @departament, notice: "Departamento creado correctamente." }
        format.json { render :show, status: :created, location: @departament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_departament
      @departament = Departament.find(params[:id])
    end
    def departament_params
      params.require(:departament).permit(:strDepartament)
    end
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/views/departaments/_form.html.haml
= form_for @departament do |f|
  - if @departament.errors.any?
    #error_explanation
      %h2= "#{pluralize(@departament.errors.count, "error")} prohibited this departament from being saved:"
      %ul
        - @departament.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-6
      = f.label :"Departamento del Producto:"
      = f.text_field :strDepartament, class:"form-control", placeholder:"Ejemplo: Videojuegos, Electronica etc."
  %br
  .actions
    = f.submit 'Aceptar', class:"btn btn-success  col-md-2"
    = link_to "Atrás", products_path, class:"btn btn-info col-md-2 "

app/views/departaments/edit.html.haml
%h1 Editing departament

= render 'form'

= link_to 'Show', @departament
\|
= link_to 'Back', departaments_path

app/views/departaments/index.html.haml
%h1 Listing departaments

%table
  %thead
    %tr
      %th Strdepartament
      %th
      %th
      %th

  %tbody
    - @departaments.each do |departament|
      %tr
        %td= departament.strDepartament
        %td= link_to 'Show', departament
        %td= link_to 'Edit', edit_departament_path(departament)
        %td= link_to 'Destroy', departament, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Departament', new_departament_path

app/views/departaments/new.html.haml
%h1 Nuevo Departamento

= render 'form'

app/views/departaments/show.html.haml
%p#notice= notice

%p
  %b Departamento:
  = @departament.strDepartament


= link_to 'Aceptar', products_path, class:"btn btn-success"