config/routes.rb
Rails.application.routes.draw do

  get 'car/index'
  resources :my_shopping_carts, only: [:create,:destroy]
  get '/add/:product_id', as: :add_to_cart, to: 'my_shopping_carts#create'
  post '/pay', to: 'payments#create'
  get '/checkout', to: 'payments#checkout'
  resources :departaments
  resources :products
  resources :suppliers
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :product
    validates :strNombreProveedor, :strDireccion, :strTelefono, :strCelular,presence: true
    validates :strNombreProveedor, length: { in: 10..100 }
    validates :strDireccion, length: { in: 10..200 }
    validates :strTelefono,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 7, :maximum => 10 }
    validates :strCelular,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 10 }
   
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]


  def index
    @suppliers = Supplier.all
  end


  def show
  end

  def new
    @supplier = Supplier.new
  end


  def edit
  end


  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: "Proveedor creado correctamente." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: "Proveedor actualizado correctamente." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:strNombreProveedor, :strDireccion, :strTelefono, :strCelular)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.haml
= form_for @supplier do |f|
  - if @supplier.errors.any?
    #error_explanation
      %h2= "#{pluralize(@supplier.errors.count, "error")} prohibited this supplier from being saved:"
      %ul
        - @supplier.errors.full_messages.each do |message|
          %li= message


  .row
    .col-6
      = f.label :"Nombre de Proveedor:"
      = f.text_field :strNombreProveedor, class:"form-control", placeholder:"Ejemplo: Marinela SA de CV"
  
    .col-6
      = f.label :"Direccion:"
      = f.text_field :strDireccion, class:"form-control", placeholder:"Ejemplo: Avenida 16 de septiembre"

  .row
    .col-6
      = f.label :"Telefono:"
      = f.text_field :strTelefono, class:"form-control", placeholder:"Ejemplo: 7312312"
    .col-6
      = f.label :"Celular:"
      = f.text_field :strCelular, class:"form-control", placeholder:"Ejemplo: 7731292374"
  
  %br
  .actions
    = f.submit 'Aceptar', class:"btn btn-success  col-md-2"
    = link_to "Atrás", suppliers_path, class:"btn btn-info col-md-2 "

app/views/suppliers/edit.html.haml
%br
.card.col-md-12.border-dark
  .card-header.text-white.bg-dark.mb-3.text-center Editar Proveedor
  .card-body
  = render 'form'

app/views/suppliers/index.html.haml
%h1 Listar Proveedores
%br

= link_to 'Nuevo Proveedor', new_supplier_path, class:"btn btn-success text-white"
%br
%br
%table
  %thead
    %tr
      %th Nombre del Proveedor
      %th Direccion
      %th Telefono
      %th Celular
      %th Acciones
    

  %tbody
    - @suppliers.each do |supplier|
      %tr
        %td= supplier.strNombreProveedor
        %td= supplier.strDireccion
        %td= supplier.strTelefono
        %td= supplier.strCelular
        %td= link_to 'Editar', edit_supplier_path(supplier), class:"btn btn-success text-white"

app/views/suppliers/new.html.haml
%br
.card.col-md-12.border-dark
  .card-header.text-white.bg-dark.mb-3.text-center Nuevo Proveedor
  .card-body
  = render 'form'
    
            

app/views/suppliers/show.html.haml
%p#notice= notice

%h4 Verefica los Datos

%p
  %b Nombre del Proveedor:
  = @supplier.strNombreProveedor
%p
  %b Descripcion:
  = @supplier.strDireccion
%p
  %b Telefono:
  = @supplier.strTelefono
%p
  %b Celular:
  = @supplier.strCelular

= link_to 'Aceptar', suppliers_path, class:"btn btn-success"